name: Build and deploy seguridad api

env:
  AZURE_WEBAPP_NAME: apiSeguridad
  AZURE_WEBAPP_PACKAGE_PATH: './API'
  DOTNET_VERSION: '8.0'

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - 'BD/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Set up dependency caching for faster builds
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: |
          dotnet restore "API/API.csproj"
          dotnet restore "Abstracciones/Abstracciones.csproj"
          dotnet restore "BC/BC.csproj"
          dotnet restore "BW/BW.csproj"
          dotnet restore "DA/DA.csproj"
          dotnet restore "Helpers/Helpers.csproj"

      - name: Build with dotnet (excluding BD project)
        run: |
          dotnet restore "API/API.csproj" --configuration Release --no-restore
          dotnet restore "Abstracciones/Abstracciones.csproj" --configuration Release --no-restore
          dotnet restore "BC/BC.csproj" --configuration Release --no-restore
          dotnet restore "BW/BW.csproj" --configuration Release --no-restore
          dotnet restore "DA/DA.csproj" --configuration Release --no-restore
          dotnet restore "Helpers/Helpers.csproj" --configuration Release --no-restore

      - name: Run tests (excluding BD project)
        run: |
          cd "API"
          dotnet test "API/API.csproj" --no-restore --verbosity normal --configuration Release || echo "No tests found or test execution failed"

      - name: dotnet publish
        run: dotnet publish "API/API.csproj" -c Release -o ./publish --no-restore

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./publish

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
          respect-funcignore: true
